FROM kong:3.6-ubuntu

# Copy minimal declarative config into image
COPY kong.coolify.min.yml /etc/kong/kong.yml

ENV KONG_DATABASE=off \
    KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml \
    KONG_PROXY_LISTEN=0.0.0.0:8000 \
    KONG_ADMIN_LISTEN=0.0.0.0:8001

CMD ["kong", "docker-start"]
